version: "3.9"
services:
  web:
    build: .
    container_name: flask-member-web
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: flask-member-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flask1234
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d # init.sql 자동 실행 폴더
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]